# -----------------------------------------------------------------------------
# UniquelyIdentifiable generates a UUID for your model
# -----------------------------------------------------------------------------
# This concern requires that you create a uuid column on your model, like so:
#
#   t.column :uuid, :uuid, null:false, index:true
#
# After including UniquelyIdentifiable, you can then call #uuid on your model
# to retrieve the UUID that will get autogenerated for you:
#
#   @my_model.uuid
#
# Version 4 UUIDs are sufficiently difficult to guess that they can be
# used for secret tokens or other unpredictable but unique identifier needs,
# even across different database tables or synchronization systems.

module UniquelyIdentifiable

  extend ActiveSupport::Concern

  included do

    validates_presence_of :uuid

    after_initialize :initialize_uuid!
    def initialize_uuid!
      if self.respond_to? :uuid
        self.uuid ||= SecureRandom.uuid
      end
    end

  end

end

